# fly.toml app configuration file generated for pds-frontpage on 2024-11-14T22:57:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pds-frontpage'
primary_region = 'lhr'

[build]

[env]
LOG_ENABLED = 'true'
PDS_BSKY_APP_VIEW_DID = 'did:web:api.bsky.app'
PDS_BSKY_APP_VIEW_URL = 'https://api.bsky.app'
PDS_CRAWLERS = 'https://bsky.network'
PDS_DATA_DIRECTORY = '/pds'
PDS_DID_PLC_URL = 'https://plc.directory'
PDS_HOSTNAME = 'frontpds.fyi'
PDS_REPORT_SERVICE_DID = 'did:plc:ar7c4by46qjdydhdevvrndac'
PDS_REPORT_SERVICE_URL = 'https://mod.bsky.app'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[mounts]]
source = 'pds_data'
destination = '/pds'
